#!/bin/bash


ACTION="$1"
REFIND_BOOT_PATH="/boot/efi/EFI/refind"

shift

PACKAGE_LIST=$@

case $ACTION in

	remove)
		countError=0
		for ix in $PACKAGE_LIST
		do
			apt-get remove -y $ix
			TEST=$( dpkg-query -s $ix 2> /dev/null| grep Status | cut -d " " -f 4 )
			if [ "$TEST" == 'installed' ];then
				let countError=countError+1
			fi
		done

		if [ $countError -ne 0 ];then
			exit 1
		else
			if [ -d "$REFIND_BOOT_PATH" ];then
				rm -rf $REFIND_BOOT_PATH
			fi
		fi
				
	;;	
esac
exit 0
