#!/bin/bash


ACTION="$1"

case $ACTION in
	remove)

		apt-get remove -y lliurex-meta-minimal-touch
		TEST=$( dpkg-query -s  lliurex-meta-minimal-touch 2> /dev/null| grep Status | cut -d " " -f 4 )
		if [ "$TEST" == 'installed' ];then
			exit 1
		fi
				
	;;	
esac
exit 0